* This release

** Coding

** Bugs

** Documentation

* Ideas

** Acceleration

*** numba acceleration

git branch numba-acceleration

Idea: wrap StochasticDynamics.do() as a JIT-compiled function, since
that (and the event functions) are where most of the time is spent. If
it generate worthwhile speed-up, extend out to other elements that are
time-consuming.

The main simulation loop seems like a good place to start as it
involves a lot of looping and drawing from probability distributions,w
which should be accelerable.

Installing the latest numba (0.51.2) installs llvmlite-0.34.0, which
only works for versions of LLVM up to 10.0.x. The latest arch version
is 11.x, so I downgraded to the latest compatible version (and also
its libraries):

#+BEGIN_SRC sh
  pacman -U https://archive.archlinux.org/packages/l/llvm/llvm-10.0.1-3-x86_64.pkg.tar.zst
  pacman -U https://archive.archlinux.org/packages/l/llvm10-libs/llvm10-libs-10.0.1-3-x86_64.pkg.tar.zst
#+END_SRC

Doesn't seem to get much speed-up, even given it's quite numerical:
there are calls to get the event distribution and to check for
equilibrium that perhaps could be refactored?

*** GPU acceleration

Will need to be [[https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/overview.html][containerised]].
